#!/usr/bin/env python
import csv
import sys
from datetime import datetime
tab_in = csv.reader(sys.stdin, dialect=csv.excel_tab)
comma_out = csv.writer(sys.stdout, dialect=csv.excel)

output = [datetime.now()]

for row in tab_in:
    output.append(row[1])

comma_out.writerow(output)
